version: '3'

services:
  app:
    build: .
    container_name: app
    restart: always
    expose: 
      - 5000
    environment:
      - BASE_URL = 'http://127.0.0.1'
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
